apiVersion: v1
kind: PersistentVolume
metadata:
  name: jenkins-docker-pv
  namespace: jenkins-docker
spec:
  storageClassName: jenkins-docker-pv
  accessModes:
  - ReadWriteOnce
  capacity:
    storage: 20Gi
  persistentVolumeReclaimPolicy: Retain
  hostPath:
    path: /data/jenkins-volume/
