apiVersion: apps/v1
kind: Deployment
metadata:
  name: jenkins-docker
spec:
  replicas: 1
  selector:
    matchLabels:
      app: jenkins-docker
  template:
    metadata:
      labels:
        app: jenkins-docker
    spec:
      containers:
      - name: jenkins
        image: visibilityspots/jenkins-docker:latest
        ports:
        - containerPort: 8080
          name: http-port
          protocol: TCP
        - containerPort: 52000
          name: jnlp-port
        volumeMounts:
          - name: jenkins-vol
            mountPath: /var/jenkins_vol
          - mountPath: /var/run 
            name: docker-sock 
      volumes:
        - name: jenkins-vol
          emptyDir: {}
        - name: docker-sock 
          hostPath: 
            path: /var/run
